version: 0.2

# environment_variables:
#   plaintext:
#     DJANGO_SETTINGS_MODULE: config.settings.test
#     SECRET_KEY: nosecret
    # DATABASE_DEFAULT_URL: sqlite:///db.sqlite3
#     DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
#     STREAM_INCOMING_PRIVATE_KEY: changeme
#     STREAM_INCOMING_PUBLIC_KEY: changeme
#     GOOGLE_API_KEY: changeme
#     OPBEAT_ENABLED: False

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - sudo apt-get update -y
      - sudo apt install -y python3-pip python3-dev nginx curl
  pre_build:
    commands:
      - pip install -r requirements.txt
      - python3 manage.py migrate 
  build:
    commands:
      - coverage run manage.py test django_cicd
      # - flake8
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'