# Generated by Django 4.1.5 on 2023-04-18 18:11

from django.db import migrations, models
import django_cicd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('lga', models.CharField(max_length=250, verbose_name='LGA')),
                ('state', models.CharField(max_length=250, verbose_name='State')),
                ('user_type', models.CharField(choices=[('Proxy', 'Proxy'), ('Principal', 'Principal')], default='', max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='Designates that user is verified and can login.', verbose_name='Verified Status')),
                ('is_updated', models.BooleanField(default=False, help_text='Designates that user has updated his/her account.', verbose_name='Updated Status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates that user can log to admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django_cicd.models.MyUserManager()),
            ],
        ),
    ]
